### ISSUE TITLE
Filter out unrelated stacktraces

### ISSUE THREAD

**Issue by filip26** [filip26/ld-cli#103]
e.g.
```
com.apicatalog.cborld.decoder.DecoderError: The encoded document must be at least 4 bytes but is [0].
	at com.apicatalog.cborld.decoder.Decoder.decode(Decoder.java:64)
	at com.apicatalog.cli.command.DecompressCmd.call(DecompressCmd.java:74)
	at com.apicatalog.cli.command.DecompressCmd.call(DecompressCmd.java:27)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at com.apicatalog.cli.App.main(App.java:82)
	at java.base@22.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```
only the first three lines are relevant

**Comment by filip26** [comment]
or hide stacktrace at all `--debug` mode
